### ISSUE TITLE
Tor hidden service volume mount is incorrect

### ISSUE THREAD

**Issue by taythebot** [hundehausen/monero-suite#19]
When you generate a config with Tor Hidden Service option enabled this is what you get currently:

```yaml
  tor:
    image: ghcr.io/hundehausen/tor-hidden-service:latest
    container_name: tor
    restart: unless-stopped
    networks:
      monero_suite_net:
        ipv4_address: 172.28.1.2
        aliases:
          - tor
    volumes:
      - tor-data:/var/lib/tor/hidden_service/
    environment:
      HS_MONEROD_MAINNET: monerod:18089:18089
```

The volume mount is `tor-data:/var/lib/tor/hidden_service/` but the hidden service data directory is actually at `/var/lib/tor/MONEROD_MAINNET`. Either the `entrypoint.sh` for `tor-hidden-service` needs to be fixed or the website needs to be updated.
